name: test

on: push

jobs:
  nushell-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - run: |
          nu -c 'http get https://raw.githubusercontent.com/NonlinearFruit/nu-gron/master/gron.nu | save -f gron.nu'
          nu -c 'http get https://raw.githubusercontent.com/NonlinearFruit/nuUnit/master/nuunit.nu | save -f nuunit.nu'
          nu nuunit.nu
